# This is a basic workflow to help you get started with Actions

name: CredentialScan

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Credential Hunter
        uses: CredentialHunter/CredentialHunterAction_Public@version-1.0
        with:
          jar_parms: '-r . -j output.json -cmax 10 --skip-refs'
          license: ${{ secrets.credential_hunter_license }}

      # Runs a set of commands using the runners shell
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
           name: scan-results
           path: output.json
